import { useMemo, useState } from "react";
import { History, RotateCcw, Search } from "lucide-react";
import type { Theme } from "../theme";
import { recordAudit, useAuditEvents, type AuditEvent } from "../auditLog";
import { appStore } from "../store";
import { partsApi } from "../partsStore";
const labels:Record<string,string>={contract:"قرارداد",part:"قطعه",assignment:"تقسیم کار",inventory:"انبار",settings:"تنظیمات",service:"سرویس"};
export default function AuditHistoryPage({t}:{t:Theme}){
 const events=useAuditEvents(),[q,setQ]=useState(""),[type,setType]=useState("all"),[message,setMessage]=useState("");
 const list=useMemo(()=>events.filter(e=>(type==="all"||e.entityType===type)&&(!q.trim()||`${e.title} ${e.actor} ${e.action}`.includes(q.trim()))),[events,q,type]);
 const rollback=(event:AuditEvent)=>{if(!event.before||!confirm(`تغییر «${event.action}» برای ${event.title} به مقدار قبلی بازگردد؟`))return;try{if(event.entityType==="contract")appStore.updateContract(event.before as any);else if(event.entityType==="part")partsApi.update(event.before as any);else if(event.entityType==="assignment")appStore.updateScheduledService(event.entityId,event.before as any);else if(event.entityType==="settings")appStore.updateCompanyAccessSettings(event.before as any);else throw new Error();recordAudit({action:"بازگردانی تغییر",entityType:event.entityType,entityId:event.entityId,title:event.title,before:event.after,after:event.before,rollbackOf:event.id});setMessage("اطلاعات به نسخه قبلی بازگردانده شد.");}catch{setMessage("این رویداد فقط برای مشاهده نگهداری می‌شود.");}};
 return <div className={`h-full overflow-auto p-5 ${t.text}`} dir="rtl"><h1 className="flex items-center gap-2 text-xl font-black"><History className="text-violet-500"/> تاریخچه تغییرات حساس</h1><p className={`mt-1 text-xs ${t.sub}`}>قیمت، قرارداد، تقسیم کار، انبار و تنظیمات همراه کاربر و زمان ثبت می‌شوند.</p><div className={`my-4 flex gap-2 rounded-2xl border p-3 ${t.panel} ${t.border}`}><div className={`flex flex-1 items-center gap-2 rounded-xl border px-3 ${t.input}`}><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="جستجو..." className="h-10 flex-1 bg-transparent text-xs outline-none"/></div><select value={type} onChange={e=>setType(e.target.value)} className={`rounded-xl border px-3 text-xs ${t.input}`}><option value="all">همه</option>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></div>{message&&<div className="mb-3 rounded-xl bg-emerald-500/10 p-3 text-xs text-emerald-500">{message}</div>}<div className="space-y-2">{list.map(event=><div key={event.id} className={`rounded-2xl border p-4 ${t.panel} ${t.border}`}><div className="flex justify-between gap-2"><div><span className="rounded-full bg-violet-500/10 px-2 py-1 text-[10px] font-bold text-violet-500">{labels[event.entityType]}</span><b className="mr-2 text-sm">{event.action} — {event.title}</b></div><span className={`text-[11px] ${t.sub}`}>{new Date(event.at).toLocaleString("fa-IR")}</span></div><div className={`mt-2 text-xs ${t.sub}`}><b>{event.actor}</b> · شناسه {event.entityId}</div>{event.before&&!["inventory","service"].includes(event.entityType)&&<div className="mt-3 text-left"><button onClick={()=>rollback(event)} className="inline-flex items-center gap-1 rounded-lg border border-amber-500 px-3 py-2 text-[11px] font-bold text-amber-600"><RotateCcw size={14}/> بازگردانی</button></div>}</div>)}{!list.length&&<div className={`rounded-2xl border border-dashed py-16 text-center text-xs ${t.border} ${t.sub}`}>هنوز تغییری ثبت نشده است.</div>}</div></div>;
}
