#!/usr/bin/env python3
"""Deterministic reviewed import. Never fuzzy-merge unspecified technical variants."""
import csv
import json
from decimal import Decimal
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
source = list(csv.DictReader((ROOT / 'data/materials/material-list-original.tsv').open(), delimiter='\t'))
rules = json.loads((ROOT / 'data/materials/review-rules.json').read_text())
rows = [{ 'code': r['code'], 'name': r['name'].strip(), 'unit': r['unit'], 'price': int(Decimal(r['price_rial'])) } for r in source]
by_code = {r['code']: r for r in rows}
assert len(by_code) == len(rows)
claimed = set()
entries = []
for group in rules['groups'] + [{'codes': [r['code']]} for r in rows if not any(r['code'] in g['codes'] for g in rules['groups'])]:
    members = [by_code[c] for c in group['codes']]
    assert not claimed.intersection(group['codes'])
    assert len({r['unit'] for r in members}) == 1
    claimed.update(group['codes'])
    # Highest price wins; ties choose the smallest numeric source code, deterministically.
    winner = sorted(members, key=lambda r: (-r['price'], int(r['code'])))[0]
    name = group.get('name', rules['names'].get(winner['code'], winner['name']))
    reviews = list(dict.fromkeys(r['note'] for r in rules['reviews'] if set(r['codes']).intersection(group['codes'])))
    entries.append({ 'code': winner['code'], 'name': name, 'unit': winner['unit'], 'price': winner['price'],
        'sources': members, 'reason': group.get('reason', ''), 'review': ' '.join(reviews) })
entries.sort(key=lambda r: int(r['code']))
assert claimed == set(by_code)
header = '''// Generated by scripts/prepare_material_catalog.py; source and review rules are tracked.
export type MaterialSource = { code: string; name: string; unit: string; price: number };
export type MaterialCatalogEntry = MaterialSource & { sources: MaterialSource[]; reason: string; review: string };
export const MATERIAL_CATALOG_VERSION = "user-materials-3.36.11";
export const MATERIAL_SOURCE_COUNT = %s;
export const MATERIAL_CATALOG: MaterialCatalogEntry[] = ''' % len(rows)
(ROOT / 'src/data/materialCatalog.ts').write_text(header + json.dumps(entries, ensure_ascii=False, indent=2) + ';\n')
with (ROOT / 'public/material-catalog-review.csv').open('w', encoding='utf-8-sig', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['کد نهایی','نام نهایی','واحد','قیمت منتخب (ریال)','کدهای قبلی','نام‌ها و قیمت‌های قبلی (ریال)','دلیل ادغام','نیازمند بررسی مشخصات'])
    for e in entries:
        writer.writerow([e['code'], e['name'], e['unit'], e['price'], ' | '.join(r['code'] for r in e['sources']),
            ' | '.join(f"{r['code']}: {r['name']} = {r['price']}" for r in e['sources']), e['reason'], e['review']])
print(f"{len(rows)} original rows -> {len(entries)} catalog items; {len(rows)-len(entries)} duplicate rows consolidated.")
