// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const DEFAULT_SUPABASE_URL = "https://fxnveupqluflmspvglng.supabase.co";
const DEFAULT_SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4bnZldXBxbHVmbG1zcHZnbG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NDY4MDgsImV4cCI6MjA2MjIyMjgwOH0.SnqhZqrql5HQndZ8O5fm-BkSRZMDj3OEXa7bon45AMA";

function sanitizeUrl(url?: unknown): string {
  if (typeof url !== 'string') return DEFAULT_SUPABASE_URL;
  const trimmed = url.trim();
  if (!trimmed || trimmed === 'undefined' || trimmed === 'null') return DEFAULT_SUPABASE_URL;
  try {
    const validUrl = trimmed.startsWith('http://') || trimmed.startsWith('https://') 
      ? new URL(trimmed) 
      : new URL(`https://${trimmed}`);
    return validUrl.origin;
  } catch {
    return DEFAULT_SUPABASE_URL;
  }
}

function sanitizeKey(key?: unknown): string {
  if (typeof key !== 'string') return DEFAULT_SUPABASE_KEY;
  const trimmed = key.trim();
  if (!trimmed || trimmed === 'undefined' || trimmed === 'null') return DEFAULT_SUPABASE_KEY;
  return trimmed;
}

const SUPABASE_URL = sanitizeUrl(import.meta.env.VITE_SUPABASE_URL);
const SUPABASE_PUBLISHABLE_KEY = sanitizeKey(import.meta.env.VITE_SUPABASE_ANON_KEY);

// هشدار در محیط توسعه: حالت سوپابیس فعال است ولی کلید وارد نشده
const isUnsetEnv = (v: unknown) => {
  if (typeof v !== 'string') return true;
  const t = v.trim();
  return !t || t === 'undefined' || t === 'null';
};
if (
  import.meta.env.DEV &&
  !isUnsetEnv(import.meta.env.VITE_SUPABASE_URL) &&
  isUnsetEnv(import.meta.env.VITE_SUPABASE_ANON_KEY)
) {
  console.warn(
    '[tlift] آدرس سوپابیس تنظیم شده ولی کلید (anon key) خالی است؛ به کلید پیش‌فرض پروژهٔ اصلی وصل می‌شوید. ' +
    'مقدار VITE_SUPABASE_ANON_KEY را در .env تکمیل کنید.'
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);